version: '3.8'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
      - JENKINS_ADMIN_LOGIN=${JENKINS_ADMIN_LOGIN}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}

volumes:
  jenkins_home:
