version: '3.8'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml

volumes:
  jenkins_home:
